Ecart/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static 
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("user/", include("user.urls", namespace="user")),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  

core/urls.py
from django.urls import path
from core import views

app_name = "core"
urlpatterns = [
    # Common
    path("", views.HomeView.as_view(), name="home"),
    path("about_us/", views.AboutView.as_view(), name="about_us"),
    # Feedback
    path(
        "feedback/create/", views.FeedbackCreateView.as_view(), name="feedback_create"
    ),
    path("feedback/list/", views.FeedbackListView.as_view(), name="feedback_list"),
    path(
        "feedback/<int:pk>/delete/",
        views.FeedbackDeleteView.as_view(),
        name="feedback_delete",
    ),
    path(
        "feedback/<int:pk>/detail/",
        views.FeedbackDetailView.as_view(),
        name="feedback_detail",
    ),
    path(
        "feedback/<int:pk>/update/",
        views.FeedbackUpdateView.as_view(),
        name="feedback_update",
    ),
    # Product
    path("product/list/", views.ProductListView.as_view(), name="product_list"),
    path("product/create/", views.ProductCreateView.as_view(), name="product_create"),
    path(
        "product/<int:pk>/detail/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
    path(
        "product/<int:pk>/update/",
        views.ProductUpdateView.as_view(),
        name="product_update",
    ),
    path(
        "product/<int:pk>/delete/",
        views.ProductDeleteView.as_view(),
        name="product_delete",
    ),
    # category
    path("category/list/", views.CategoryListView.as_view(), name="category_list"),
    path("product_by_category/<int:pk>/list/",views.ProductByCategoryView.as_view(), name="product_by_category",),
   
    # Cart
    path("cart/product/<int:pk>/add/", views.AddToCartView.as_view(), name="add_to_cart"),
    path("cart/", views.CartView.as_view(), name="cart"),
    path("cart_delete/", views.CartView.as_view(), name="cart_delete"),

    # delivery
    path("delivery/", views.DeliveryView.as_view(), name="delivery"),
    # shipment
    path("shipment/", views.ShipmentView.as_view(), name="shipment"),
    # ordersummary
    path("ordersummary/", views.OrdersummaryView.as_view(), name="ordersummary"),
    #orderplaced
     path("ordr_placed/", views.OrderplacedView.as_view(), name="ordr_placed"),
    # checkout
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    # cancelorder
    path("cancelorder/", views.CancelorderView.as_view(), name="cancelorder"),
     # canceltemplate
    path("canceltemplate/", views.CanceltemplateView.as_view(), name="canceltemplate"),
    # payment
    path("payment/", views.PaymentView.as_view(), name="payment"),
    # payment success
    path("paymentsuccess/", views.PaymentsuccessView.as_view(), name="paymentsuccess"),
    path("add_details/", views.AdddetailView.as_view(), name="add_details"),
    path("addnew_address/", views.AddnewaddressView.as_view(), name="addnew_address"),
    #dashboard
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    #search
    path("product/search/",views.ProductSearchView.as_view(),name="product_search"),



]

core/models.py
from django.db import models
from django.db.models import F,Q,Sum,Count,Avg
from django.contrib.auth import get_user_model


class FeedbackModel(models.Model):
    name = models.CharField(max_length=64)
    email = models.EmailField()
    subject = models.CharField(max_length=120)
    message = models.TextField(max_length=500)
    status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.subject}"


# Category


class CategoryModel(models.Model):
    name = models.CharField(max_length=64)
    parent = models.ForeignKey("self", on_delete=models.SET_NULL, null=True, blank=True)
    status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name}"


# Unit model


class UnitModel(models.Model):
    name = models.CharField(max_length=64)
    symbol = models.CharField(max_length=8)
    convertion_rate = models.FloatField()
    secondary = models.ForeignKey(
        "self", on_delete=models.SET_NULL, null=True, blank=True
    )
    status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name}"


# product


class ProductModel(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField(max_length=500)
    price = models.FloatField()
    size = models.CharField(max_length=10)
    image = models.ImageField(upload_to="product/image/", default="default/product.png")
    category = models.ManyToManyField(CategoryModel)
    status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name}"


USER = get_user_model()

# Cart Model
class CartModel(models.Model):
    user = models.ForeignKey(USER, on_delete=models.CASCADE)
    checked_out = models.BooleanField(default=False)
    status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    size = models.CharField(default=0, max_length=5)

    def items(self):
        cart_items = CartItemModel.objects.filter(
            cart=self,
            status=True,
        )
        return cart_items

    def total(self):
        amount = CartModel.objects.aggregate(
            amount=Sum(F("cartitemmodel__product__price") * F("cartitemmodel__quantity"))
        ).get("amount", 0)
        return amount

    def __str__(self):
        return f"{self.user}"


# Cart Item Model
class CartItemModel(models.Model):
    cart = models.ForeignKey(CartModel, on_delete=models.CASCADE)
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.product}({self.quantity})"

core/forms.py
from django import forms
from core import models


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = models.FeedbackModel
        # fields = "__all__" #["name", "message", "email", ]
        exclude = ('status', )
 #product

class ProductForm(forms.ModelForm):
    class Meta:
        model = models.ProductModel
        # fields = "__all__" #["name", "message", "email", ]
        exclude = ("status","created_on","updated_on" )


class CategoryForm(forms.ModelForm):
    class Meta:
        model = models.CategoryModel
        # fields = "__all__" #["name", "message", "email", ]
        exclude = ("status","created_on","updated_on" )

core/views.py
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic as views

from core import models as core_models
from core.forms import FeedbackForm, ProductForm
from user import models as user_models
from django.db.models import F, Q



# home view
class HomeView(views.TemplateView):
    template_name = "core/home.html"

    extra_context = {"products": core_models.ProductModel.objects.filter(status=True)}


# about_us view
class AboutView(views.TemplateView):
    template_name = "core/about_us.html"




# ================================= FEEDBACK ================================= #


# feedback create view
class FeedbackCreateView(views.CreateView):
    template_name = "core/feedback_create.html"
    model = core_models.FeedbackModel
    form_class = FeedbackForm
    success_url = reverse_lazy("core:home")


class FeedbackListView(views.ListView):
    template_name = "core/feedback_list.html"
    model = core_models.FeedbackModel
    form_class = FeedbackForm
    success_url = reverse_lazy("core:home")


class FeedbackDeleteView(views.ListView):
    template_name = "core/feedback_delete.html"
    model = core_models.FeedbackModel
    form_class = FeedbackForm
    success_url = reverse_lazy("core:home")


class FeedbackDetailView(views.ListView):
    template_name = "core/feedback_detail.html"
    model = core_models.FeedbackModel
    form_class = FeedbackForm
    success_url = reverse_lazy("core:home")


class FeedbackUpdateView(views.ListView):
    template_name = "core/feedback_update.html"
    model = core_models.FeedbackModel
    form_class = FeedbackForm
    success_url = reverse_lazy("core:home")


# ================================= FEEDBACK END ================================= #


# ================================= PRODUCT START ================================= #

# Product list
class ProductListView(views.ListView):
    template_name = "core/product_list.html"
    model = core_models.ProductModel
    context_object_name = "products"


# Product create
class ProductCreateView(views.CreateView):
    template_name = "core/product_create.html"
    model = core_models.ProductModel
    form_class = ProductForm
    success_url = reverse_lazy("core:product_list")


# Product detail
class ProductDetailView(views.DetailView):
    template_name = "core/product_detail.html"
    model = core_models.ProductModel
    context_object_name = "product"


# Product update
class ProductUpdateView(views.UpdateView):
    template_name = "core/product_update.html"
    model = core_models.ProductModel
    form_class = ProductForm
    success_url = reverse_lazy("core:product_list")


# Product delete
class ProductDeleteView(views.DeleteView):
    template_name = "core/product_delete.html"
    model = core_models.ProductModel
    success_url = reverse_lazy("core:product_list")


# ================================= PRODUCT END ================================= #


# ================================= CATEGORY START ================================= #


class ProductByCategoryView(views.ListView):
    template_name = "core/product_list.html"
    model = core_models.ProductModel
    context_object_name = "products"

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        pk = self.kwargs.get("pk", None)
        qs = qs.filter(category__id=pk)
        return qs


class CategoryListView(views.ListView):
    template_name = "core/category/category_list.html"
    model = core_models.CategoryModel
    context_object_name = "categories"


# =================================CATEGORY END================================= #

# cart


class AddToCartView(views.View):
    def get(self, request, pk):
        # try:
        user = request.user
        product = core_models.ProductModel.objects.get(id=pk)
        cart, cart_created = core_models.CartModel.objects.get_or_create(
            user=user, checked_out=False
        )
        cart_item, cart_item_created = core_models.CartItemModel.objects.get_or_create(
            cart=cart, product=product
        )
        if not cart_item_created:
            cart_item.quantity += 1

        cart_item.save()
        messages.success(request, "Product added successfully!")
        # except Exception as e:
        #     print(e)
        #     messages.error(request, f"Product couldn't add! ERROR:-{e}")
        url = request.META.get("HTTP_REFERER")
        return redirect(url)


# cart
class CartView(views.TemplateView):
    template_name = "core/checkout/cart.html"


# cartremove
class CartDeleteView(views.DeleteView):
    template_name = "core/checkout/cart_delete.html"
    model = core_models.CartModel


# delivery
class DeliveryView(views.TemplateView):
    model = user_models.AddressModel
    template_name = "core/delivery/delivery_address.html"
    context_object_name = "addresss"


# shipment
class ShipmentView(views.TemplateView):
    template_name = "core/delivery/shipment_details.html"


# order summary


class OrdersummaryView(views.TemplateView):
    template_name = "core/delivery/order_summary.html"


# order placed
class OrderplacedView(views.TemplateView):
    template_name = "core/orderplaced/ordr_placed.html"


# checkout
class CheckoutView(views.TemplateView):
    template_name = "core/checkout/checkout.html"


class CancelorderView(views.TemplateView):
    template_name = "core/checkout/cancelorder.html"


class CanceltemplateView(views.TemplateView):
    template_name = "core/checkout/canceltemplate.html"


# payment
class PaymentView(views.TemplateView):
    template_name = "core/payment/payment.html"


# payment success
class PaymentsuccessView(views.TemplateView):
    template_name = "core/payment/paysuccess.html"


# add more  details
class AdddetailView(views.TemplateView):
    template_name = "core/user/add_details.html"


# add new address
class AddnewaddressView(views.TemplateView):
    template_name = "user/addnew_address.html"

# dashbboard
class DashboardView(views.TemplateView):
    template_name = "core/dashboard/dashboard.html"

#search
class ProductSearchView(views.ListView):
    template_name = "core/list.html"
    model = core_models.ProductModel
    context_object_name = "products"

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        q = self.request.GET.get("q", None)
        qs = qs.filter(Q(name__icontains=q) | Q(category__name__icontains=q))
        return qs

templates/core/feedback_create.html
{% extends 'base.html' %} {% block content %}

<div class="container py-5">
  <div class="row">
    <div class="col-lg-6">
      <i><h1>Feedback form</h1></i>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos fuga porro quisquam 
        at, architecto nobis libero iste saepe? Vel eveniet inventore adipisci cum minus ea distinction
         quibusdam, magni sapiente ipsum.</p>
        <li>we would like your feedback to improve our website.</li>
     
      <li>
        what is your opinion about us ?</li>
      
    </div>
    <div class="col-lg-6">
      <div class="card">
        <div class="card-body">
          <form action="" method="post">
            {% csrf_token %}
            <table>
                <tbody>
                    {{form.as_p}}
                </tbody>
            </table>
            <button class="btn btn-primary" type="submit"> post Comment</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/core/feedback_detail.html
{% extends "base.html" %} {% block content %}

<section class="py-5">
  <div class="container">
    <div class="row">
      <div class="col">
        <h2 class="text-center">Feedback Detail</h2>
        <hr />
      </div>
    </div>
    <div class="row">
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Name: {{feedback.name}}</h5>
            <p class="card-text">Subject: {{feedback.subject}}</p>
            <p class="card-text">Message: {{feedback.message}}</p>
            <p class="card-text">Last updated: {{feedback.updated_on}}</p>
            <div>
              <a href="{% url 'core:feedback_update' feedback.id %}" class="btn btn-success">
                <i class="fa-solid fa-pen"></i>
                Update
              </a>
              <a href="{% url 'core:feedback_delete' feedback.id %}" class="btn btn-danger">
                <i class="fa-solid fa-trash"></i>
                Delete
              </a>
            </div>                                                                              
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/core/feedback_list.html
{% extends "base.html" %} {% block content %}

<section class="py-5">
  <div class="container">
    <div class="row">
        <div class="col">
            <h2 class="text-center">Feedback List</h2>
            <hr>
        </div>
    </div>
    <div class="row">
      <div class="col">
        <table class="table table-bordered align-middle">
          <thead>
            <tr class="text-center fw-bold">
              <th >#</th>
              <th>Name</th>
              <th>Subject</th>
              <th>Last Updated</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for feedback in feedbacks %}

            <tr>
              <td class="text-center fw-bold">{{forloop.counter}}</td>
              <td>{{feedback.name}}</td>
              <td>{{feedback.subject}}</td>
              <td>{{feedback.updated_on|date}}</td>
              <td class="text-center">
                <a href="{% url 'core:feedback_detail' feedback.id %}" class="btn btn-info">
                    <i class="fa-solid fa-eye"></i>
                    Detail
                </a>
                <a href="{% url 'core:feedback_update' feedback.id %}" class="btn btn-success">
                    <i class="fa-solid fa-pen"></i>
                    Update
                </a>
                <a href="{% url 'core:feedback_delete' feedback.id %}" class="btn btn-danger">
                    <i class="fa-solid fa-trash"></i>
                    Delete
                </a>
              </td>
            </tr>

            {% empty %}
            <tr>
              <td colspan="4">No feedbacks!</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/core/home.html
{% extends 'base.html' %} 
{% block content %}
<section style="background-image: url(https://thumbs.dreamstime.com/b/pink-blue-soft-color-mixed-background-painting-art-pastel-abstract-colorful-art-wallpaper-abstract-colorful-bright-color-soft-117208177.jpg)"> 
  <div class="m-5">
    <div class="row">
      <div class="col">
        <span style="font-family: 'Times New Roman', Times, serif">
          <ol style="color:brown">
          <h1 class="text-center">WELCOME
          <i class="fa-solid fa-handshake"></i>
          </h1></ol>
        </span>
      </div>
    </div>
  </div>
  <!--#caurosel -->
  <div class="container">
  <section class="hero-section">
    <div
      id="carouselExampleControls"
      class="carousel slide"
      data-bs-ride="carousel"
    >
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="media/product/banner.jpeg" height="550px" class="d-block w-100" alt="..." />
        </div>
        <div class="carousel-item">
          <img src="media/product/banner1.jpeg" height="550px" class="d-block w-100" alt="..." />
        </div>
        <div class="carousel-item">
          <img src="media/product/shoes.jpeg" height="550px" class="d-block w-100" alt="..." />
        </div>
      </div>
      <button
        class="carousel-control-prev"
        type="button"
        data-bs-target="#carouselExampleControls"
        data-bs-slide="prev"
      >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button
        class="carousel-control-next"
        type="button"
        data-bs-target="#carouselExampleControls"
        data-bs-slide="next"
      >
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </section>
  <!-- <!-- #caurosel -->

  <section class="pt-5 pb-5">
  <div class="container">
    <div class="row">
      <div class="col-6">
        <ol style="color:brown">
        <h3 class="mb-3">Last minute deals </h3></ol>
      </div>
      <div class="col-6 text-right">
        
        <a class="btn btn-primary mb-3 mr-1" href="#carouselExampleIndicators2" role="button" data-slide="prev">
          <i class="fa fa-arrow-left"></i>
        </a>
        <a class="btn btn-primary mb-3 " href="#carouselExampleIndicators2" role="button" data-slide="next">
          <i class="fa fa-arrow-right"></i>
        </a>
      </div>
      <div class="col-12">
        <div id="carouselExampleIndicators2" class="carousel slide" data-ride="carousel">

          <div class="carousel-inner">
            <div class="carousel-item active">
              <div class="row">

                <div class="col-md-4 mb-3">
                <div class="card border-warning text-warning">
                  <div class="card h-6">
                    <img class="img-fluid" alt="100%x280" src="/media/default/chain.jpeg" style="height: 200px;">
                    <div class="card-body">
                      <ol style="color:goldenrod">
                      <h4 style="height: 50px;" class="card-title">Special chains for you</h4></ol>
                    </div>
                  </div>
                </div>
                </div>
                <div class="col-md-4 mb-3">
                  <div class="card border-danger text-danger">
                  <div class="card h-6">
                    <img class="img-fluid" alt="100%x280"src="/media/default/pinkshoes.jpeg" style="height: 200px;">
                    <div class="card-body">
                      <ol style="color:rgb(252, 134, 154)">
                      <h4 style="height: 50px;" class="card-title">Special offers for girls sneakers</h4></ol>
                      <p class="card-text"></p>
                    </div>
                  </div>
                </div>
                </div>
                <div class="col-md-4 mb-3">
                <div class="card border-primary text-primary">
                  <div class="card">
                    <img class="img-fluid"  alt="100%x280" src="/media/default/iu73.jpeg" style="height: 200px;">
                    <div class="card-body">
                      <ol style="color:rgb(66, 32, 218)"> 
                      <h4 style="height: 50px;" class="card-title">what about the Redmi 11 Pro-Max </h4></ol>
                      <!-- <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> -->
                    </div>
                  </div>
                </div>
                </div>

              </div>
            </div>
            <div class="carousel-item">
              <div class="row">

                <div class="col-md-4 mb-3">
                <div class="card border-info text-info">
                  <div class="card">
                    <img class="img-fluid" alt="100%x280" src="/media/default/ring.jpeg" style="height: 200px;"></ol>
                    <div class="card-body">
                      <ol style="color: darkmagenta">
                      <h4 style="height: 50px;" class="card-title">Have you seen the new styles?</h4></ol>
                    </div>
                  </div>
                </div>
                </div>
                <div class="col-md-4 mb-3">
                <div class="card border-success text-success">
                  <div class="card">
                    <img class="img-fluid" alt="100%x280" src="/media/default/kurti.jpeg" 
                    style="height: 200px;">
                    <div class="card-body">
                      <ol style="color: darkgreen">
                      <h4 style="height: 50px;" class="card-title">Check out the new trends</h4></ol>
                    </div>
                  </div>
                </div>
                </div>
                <div class="col-md-4 mb-3">
                <div class="card border-danger text-danger">
                  <div class="card">
                    <img class="img-fluid" alt="100%x280" src="/media/default/beauty.jpeg" style="height: 200px;">
                    <div class="card-body">
                      <ol style="color:brown">
                      <h4 style="height: 50px;" class="card-title">Christian Dior</h4></ol>
                    </div>
                  </div>
                </div>
                </div>

              </div>
            </div>
            <div class="carousel-item">
              <div class="row">
                <div class="col-md-4 mb-3">
                  <div class="card border-warning text-warning">
                  <div class="card">
                    <img class="img-fluid" alt="100%x280" src="/media/default/bread.jpeg" style="height: 200px;">
                    <div class="card-body">
                      <ol style="color:rgb(240, 143, 16)">
                      <h4 style="height: 50px;" class="card-title">Good food choices for you!</h4></ol>
                    </div>
                  </div>
                </div>
                </div>
                <div class="col-md-4 mb-3">
                <div class="card border-dark text-dark">
                  <div class="card">
                    <img class="img-fluid" alt="100%x280" src="/media/default/eyewear.jpeg" style="height: 200px;">
                    <div class="card-body">
                      <ol style="color:rgb(16, 214, 240)">
                      <h4 style="height: 50px;" class="card-title">Think you are spectacular</h4></ol>
                    </div>
                  </div>
                </div>
                </div>
                <div class="col-md-4 mb-3">
                <div class="card border-danger text-danger">
                  <div class="card">
                    <img class="img-fluid" alt="100%x280" src="/media/default/heels.jpeg" style="height: 200px;">
                    <div class="card-body">
                      <ol style="color:darkred">
                      <h4 style="height: 50px;" class="card-title">Heels never goes out of style</h4></ol>
        
                    </div>
                  </div>
                </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </section>
  <section class="py-5">
  <div class="container">
    <div class="row">
      <div class="col">
      <ol style="color:blueviolet">
      <b> <i><h2 class="text-center">products for you</ol></h2></i> </b>
        <hr />
      </div>
    </div>
      </div>

    <div class="row row-cols-lg-4 g-3">
      {% for product in products %}
      <div class="col">
        <div class="card">
          <img src="{{product.image.url}}" class="card-img-top" alt="..." height="200px" />
          <div class="card-body">
            <h5 class="card-title overflow-hidden" style="width: 200px; height: 28px;">
              <a
                href="{% url 'core:product_detail' product.id %}"
                class="link-primary "
                  >{{product.name}}</a
              >

            </h5>
            <p class="card-text">Price: {{product.price}}</p>
            <p class="card-text overflow-hidden" style="height: 60px;">Description: {{product.description}}</p>
            <!-- categories -->
            <div>
              <p class="card-text">Categories</p>
              <ul>
                {% for category in product.category.all %}
                <li>{{category}}</li>
                {% endfor %}
              </ul>
            </div>
            <p class="card-text text-muted fst-italic">
              Last updated: {{product.updated_on|date}}
            </p>
          </div>
          <!-- <div class="card-footer">
            <a href="{% url 'core:add_to_cart' product.id %}" class="btn btn-primary">
              <i class="fa-solid fa-cart-shopping"></i>
              Add to cart
            </a>
          </div> -->
        </div>
      </div>
      {% empty %}
      <div class="col">
        <p>no product found</p>
      </div>
      {% endfor %}
    </div>
  </div>
  </section>
            </div>
        </div>
    </div>
  </section>
</section> 
</Body>
{% endblock content %}





        





        

templates/core/product_detail.html
{% extends 'base.html' %} {% block content %}

<div class="container py-5">
  <div class="row">
    <div class="col-lg-6">
      <h1>Product Detail</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6">
      <img src="{{product.image.url}}" class="img img-thumnail" width="100%" alt="">
    </div>
    <div class="col-lg-6">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">{{product.name}}</h4>
          <p class="card-text">INR {{product.price}}</p>
          <div class="rating-container ">
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-regular fa-star"></i>
          </div>
          <p class="card-text">{{product.description}}</p>
          <!-- <div>
            <a href="{% url 'core:product_update' product.id %}" class="btn btn-primary">Update</a>
            <a href="{% url 'core:product_delete' product.id %}" class="btn btn-danger">Delete</a>
          </div> -->
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/core/product_list.html
{% extends 'base.html' %}
{% block content %}
<section style="background-image: url(https://i.pinimg.com/originals/80/7c/33/807c33ff38cef690083555dd4f6396bc.jpg)">
<section class="py-5">
  <div class="container">
    <div class="row">
      <div class="col">
        <ol style="color:rgb(66, 32, 218)"> 
        <h2 class="text-center">Products for you</h2></ol>
        <hr />
      </div>
    </div>

    <div class="row row-cols-lg-4 g-3">
      {% for product in products %}
      <div class="col">
        <div class="card">
          <img src="{{product.image.url}}" class="card-img-top" alt="..." height="200px" />
          <div class="card-body">
            <h5 class="card-title overflow-hidden" style="width: 200px; height: 28px;">
              <a
                href="{% url 'core:product_detail' product.id %}"
                class="link-primary "
                 >{{product.name}}</a
              >
            </h5>
             <p class="card-text">Price: {{product.price}}</p>
            <p class="card-text overflow-hidden" style="height: 50px;">Description: {{product.description}}</p>
            <p class="card-text">Size: {{product.size}}</p>
            <!-- categories -->
           
            <div>
              <p class="card-text">Categories</p>
              <ul>
                {% for category in product.category.all %}
                <li>{{category}}</li>
                {% endfor %}
              </ul>
            </div>
            <!-- <p class="card-text">Category: {{product.category}}</p> -->
            <p class="card-text text-muted fst-italic">
              Last updated: {{product.updated_on|date}}
            </p>
          </div>
          <div class="card-footer">
            <a href="{% url 'core:add_to_cart' product.id %}" class="btn btn-primary">
              <i class="fa-solid fa-cart-shopping"></i>
              Add to cart
            </a>
          </div>
        </div>
      </div>
      {% empty %}
      <div class="col">
        <p>no product found</p>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
</section>
{% endblock content %}