Ecart/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static 
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("user/", include("user.urls", namespace="user")),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  

core/urls.py
from django.urls import path
from core import views

app_name = "core"
urlpatterns = [
    # Common
    path("", views.HomeView.as_view(), name="home"),
    path("about_us/", views.AboutView.as_view(), name="about_us"),
    # Feedback
    path(
        "feedback/create/", views.FeedbackCreateView.as_view(), name="feedback_create"
    ),
    path("feedback/list/", views.FeedbackListView.as_view(), name="feedback_list"),
    path(
        "feedback/<int:pk>/delete/",
        views.FeedbackDeleteView.as_view(),
        name="feedback_delete",
    ),
    path(
        "feedback/<int:pk>/detail/",
        views.FeedbackDetailView.as_view(),
        name="feedback_detail",
    ),
    path(
        "feedback/<int:pk>/update/",
        views.FeedbackUpdateView.as_view(),
        name="feedback_update",
    ),
    # Product
    path("product/list/", views.ProductListView.as_view(), name="product_list"),
    path("product/create/", views.ProductCreateView.as_view(), name="product_create"),
    path(
        "product/<int:pk>/detail/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
    path(
        "product/<int:pk>/update/",
        views.ProductUpdateView.as_view(),
        name="product_update",
    ),
    path(
        "product/<int:pk>/delete/",
        views.ProductDeleteView.as_view(),
        name="product_delete",
    ),
    # category
    path("category/list/", views.CategoryListView.as_view(), name="category_list"),
    path("product_by_category/<int:pk>/list/",views.ProductByCategoryView.as_view(), name="product_by_category",),
   
    # Cart
    path("cart/product/<int:pk>/add/", views.AddToCartView.as_view(), name="add_to_cart"),
    path("cart/", views.CartView.as_view(), name="cart"),
    path("cart_delete/", views.CartView.as_view(), name="cart_delete"),

    # delivery
    path("delivery/", views.DeliveryView.as_view(), name="delivery"),
    # shipment
    path("shipment/", views.ShipmentView.as_view(), name="shipment"),
    # ordersummary
    path("ordersummary/", views.OrdersummaryView.as_view(), name="ordersummary"),
    #orderplaced
     path("ordr_placed/", views.OrderplacedView.as_view(), name="ordr_placed"),
    # checkout
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    # cancelorder
    path("cancelorder/", views.CancelorderView.as_view(), name="cancelorder"),
     # canceltemplate
    path("canceltemplate/", views.CanceltemplateView.as_view(), name="canceltemplate"),
    # payment
    path("payment/", views.PaymentView.as_view(), name="payment"),
    # payment success
    path("paymentsuccess/", views.PaymentsuccessView.as_view(), name="paymentsuccess"),
    path("add_details/", views.AdddetailView.as_view(), name="add_details"),
    path("addnew_address/", views.AddnewaddressView.as_view(), name="addnew_address"),
    #dashboard
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    #search
    path("product/search/",views.ProductSearchView.as_view(),name="product_search"),



]

user/urls.py
from core import views
from django.urls import path

from user import views

app_name = "user"

urlpatterns = [
    path("signup/", views.UserCreateView.as_view(), name="user_signup"),
    path("login/", views.UserLoginView.as_view(), name="user_login"),
    path("logout/", views.UserLogoutView.as_view(), name="user_logout"),
    # address
    path("address/create/", views.AddressCreateView.as_view(), name="address_create"),

    # 
    path("profile/create/", views.ProfileCreateView.as_view(), name="profile_create"),
    path("profile/detail/", views.ProfileDetailView.as_view(), name="profile_detail"),
    path("profile/<int:pk>/update/",views.ProfileUpdateView.as_view(),name="profile_update"), 
    
]

templates/includes/footer.html
<!-- Footer -->

<footer class="text-center text-lg-start bg-dark text-muted">
  <!-- Section: Social media -->
  <section
    class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
  >
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #3b5998"
        href="#!"
        role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #3b984a"
        href="#!"
        role="button"
        ><i class="fa-brands fa-whatsapp"></i>
      </a>
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #55acee"
        href="#!"
        role="button"
        ><i class="fab fa-twitter"></i
      ></a>
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #dd4b39"
        href="#!"
        role="button"
        ><i class="fab fa-google"></i
      ></a>
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #ac2bac"
        href="#!"
        role="button"
        ><i class="fab fa-instagram"></i
      ></a>
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #0082ca"
        href="#!"
        role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Shop E
          </h6>
        </div>
        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Useful links</h6>
          <p>
            <a href="{% url 'core:about_us' %}" class="text-reset">About us</a>
          </p>
          <p>
            <a href="{% url 'core:dashboard' %}" class="text-reset">Dashboard</a>
          </p>


          <p>
            <a href="{% url 'core:feedback_create' %}" class="text-reset"
              >feedback</a
            >
          </p>
          <p>
            <a href="#!" class="text-reset">settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact US</h6>
          <p><i class="fas fa-home me-3"></i> INDIA</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            shope@yahoo.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div
    class="text-center p-4"
    style="background-color: rgba(230, 15, 15, 0.027)"
  >
    © 2022 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">Shop E.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg bg-info shadow-sm">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'core:home' %}">Ekart</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'core:home' %}"
            >Home</a
          >
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:category_list' %}">Category</a>
        </li>
      <li class="nav-item dropdown">
        <a
          class="nav-link dropdown-toggle"
          href="#"
          role="button"
          data-bs-toggle="dropdown"
          aria-expanded="false"
        >
          Product
        </a>
        <ul class="dropdown-menu">
          <li>
            <a class="dropdown-item" href="{% url 'core:product_list' %}"
              >Product list</a
            >
          </li>
          <!-- <li>
            <a class="dropdown-item" href="{% url 'core:product_create' %}"
              >Create Product</a
            >
          </li> -->
        </ul>
      </li>
     <li>
      {% if user.is_authenticated %} 
        
        <a href="{% url 'user:profile_detail' %}" class="btn btn-success text-light text-uppercase">
          {{user}}
        </a> 
        {% else %}             
        <a href="{% url 'user:user_signup' %}" class="btn btn-primary ms-2 me-2">
          Sign Up
        </a>
        {% endif %}
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item me-3">
        <a href="{% url 'user:user_logout' %}" class="btn btn-danger ms-2 me-2">Signout</a>
        {% else %}
        <a href="{% url 'user:user_login' %}" class="btn btn-success ms-2 me-2">
          Sign In
        </a>
      {% endif %}
     </li>
      <li class="nav-item dropdown">
        <a
          class="nav-link dropdown-toggle"
          href="{% url 'core:cart' %}"
          role="button"
          data-bs-toggle="dropdown"
          aria-expanded="false"
        >
          Cart
          <span class="badge rounded-pill text-bg-danger"
            >{{cart.items.count}}</span
          >
        </a>
        <ul class="dropdown-menu">
          <li class="dropdown-item d-flex justify-content-between fw-bold">
            <span>Item</span>
            <span>Qty</span>
          </li>
          {% for item in cart.items %}
          <li class="dropdown-item d-flex justify-content-between">
            <a
              class="link-primary"
              href="{% url 'core:product_detail' item.product.id %}"
            >
              {{item.product}}
            </a>
            <span class="fw-bold">{{item.quantity}}</span>
          </li>
          {% empty %}
          <li>Nothing Found!</li>
          {% endfor %}
          <li class="dropdown-item d-flex justify-content-between fw-bold text-bg-primary">
            <a href="{% url 'core:checkout' %}" class="link-light">Checkout</a>
          </li>
        </ul>
      </li> 
    </ul>
    <!-- <li class="nav-item dropdown">
      <a
        class="nav-link dropdown-toggle"
        href="#"
        role="button"
        data-bs-toggle="dropdown"
        aria-expanded="false"
      >
      delivery
      </a>
    
    <ul class="dropdown-menu">
       <li>
        <a class="dropdown-item" href="{% url 'core:delivery' %}"
          >Delivery Address</a
        >
      </li>  -->
      <!-- <li>
        <a class="dropdown-item" href="{% url 'core:shipment' %}"
          >Shipment Details</a
        >
      </li> -->
      <!-- <li>
        <a class="dropdown-item" href="{% url 'core:ordersummary' %}"
          >Order Summary</a
        >
      </li> -->
    <!-- </ul>
  </li> -->
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <!-- <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <a
          class="nav-link active"
          aria-current="page"
          href="{% url 'core:checkout' %}"
          >check out</a
        >
      </ul>
      </li> -->
      <!-- <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a
              class="nav-link active"
              aria-current="page"
              href="{% url 'core:payment' %}"
              >payment</a>
          </li>
      <div> -->

     
        <form action="{% url 'core:product_search' %}" class="d-flex" role="search">
          <input
          class="form-control me-2"
          type="search"
          placeholder="Search"
          aria-label="Search"
          name="q"
        />
          <button class="btn btn-primary" type="submit">Search</button>
        </form>
      </div>
    </div>
  </div>   
  </nav> 

templates/includes/scripts.html
{% load static %}

<script src="{% static 'jquery-3.6.1.min.js' %}"></script>
<script src="{% static 'bootstrap-5.2.2-dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'fontawesome-free-6.2.0-web/js/all.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>






<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>     
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
<script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

templates/includes/styles.html
{% load static %}

<link rel="stylesheet" href="{% static 'bootstrap-5.2.2-dist/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'fontawesome-free-6.2.0-web/css/all.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">