Ecart/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static 
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("user/", include("user.urls", namespace="user")),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  

core/urls.py
from django.urls import path
from core import views

app_name = "core"
urlpatterns = [
    # Common
    path("", views.HomeView.as_view(), name="home"),
    path("about_us/", views.AboutView.as_view(), name="about_us"),
    # Feedback
    path(
        "feedback/create/", views.FeedbackCreateView.as_view(), name="feedback_create"
    ),
    path("feedback/list/", views.FeedbackListView.as_view(), name="feedback_list"),
    path(
        "feedback/<int:pk>/delete/",
        views.FeedbackDeleteView.as_view(),
        name="feedback_delete",
    ),
    path(
        "feedback/<int:pk>/detail/",
        views.FeedbackDetailView.as_view(),
        name="feedback_detail",
    ),
    path(
        "feedback/<int:pk>/update/",
        views.FeedbackUpdateView.as_view(),
        name="feedback_update",
    ),
    # Product
    path("product/list/", views.ProductListView.as_view(), name="product_list"),
    path("product/create/", views.ProductCreateView.as_view(), name="product_create"),
    path(
        "product/<int:pk>/detail/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
    path(
        "product/<int:pk>/update/",
        views.ProductUpdateView.as_view(),
        name="product_update",
    ),
    path(
        "product/<int:pk>/delete/",
        views.ProductDeleteView.as_view(),
        name="product_delete",
    ),
    # category
    path("category/list/", views.CategoryListView.as_view(), name="category_list"),
    path("product_by_category/<int:pk>/list/",views.ProductByCategoryView.as_view(), name="product_by_category",),
   
    # Cart
    path("cart/product/<int:pk>/add/", views.AddToCartView.as_view(), name="add_to_cart"),
    path("cart/", views.CartView.as_view(), name="cart"),
    path("cart_delete/", views.CartView.as_view(), name="cart_delete"),

    # delivery
    path("delivery/", views.DeliveryView.as_view(), name="delivery"),
    # shipment
    path("shipment/", views.ShipmentView.as_view(), name="shipment"),
    # ordersummary
    path("ordersummary/", views.OrdersummaryView.as_view(), name="ordersummary"),
    #orderplaced
     path("ordr_placed/", views.OrderplacedView.as_view(), name="ordr_placed"),
    # checkout
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    # cancelorder
    path("cancelorder/", views.CancelorderView.as_view(), name="cancelorder"),
     # canceltemplate
    path("canceltemplate/", views.CanceltemplateView.as_view(), name="canceltemplate"),
    # payment
    path("payment/", views.PaymentView.as_view(), name="payment"),
    # payment success
    path("paymentsuccess/", views.PaymentsuccessView.as_view(), name="paymentsuccess"),
    path("add_details/", views.AdddetailView.as_view(), name="add_details"),
    path("addnew_address/", views.AddnewaddressView.as_view(), name="addnew_address"),
    #dashboard
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    #search
    path("product/search/",views.ProductSearchView.as_view(),name="product_search"),



]

core/models.py
from django.db import models
from django.db.models import F,Q,Sum,Count,Avg
from django.contrib.auth import get_user_model


class FeedbackModel(models.Model):
    name = models.CharField(max_length=64)
    email = models.EmailField()
    subject = models.CharField(max_length=120)
    message = models.TextField(max_length=500)
    status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.subject}"


# Category


class CategoryModel(models.Model):
    name = models.CharField(max_length=64)
    parent = models.ForeignKey("self", on_delete=models.SET_NULL, null=True, blank=True)
    status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name}"


# Unit model


class UnitModel(models.Model):
    name = models.CharField(max_length=64)
    symbol = models.CharField(max_length=8)
    convertion_rate = models.FloatField()
    secondary = models.ForeignKey(
        "self", on_delete=models.SET_NULL, null=True, blank=True
    )
    status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name}"


# product


class ProductModel(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField(max_length=500)
    price = models.FloatField()
    size = models.CharField(max_length=10)
    image = models.ImageField(upload_to="product/image/", default="default/product.png")
    category = models.ManyToManyField(CategoryModel)
    status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name}"


USER = get_user_model()

# Cart Model
class CartModel(models.Model):
    user = models.ForeignKey(USER, on_delete=models.CASCADE)
    checked_out = models.BooleanField(default=False)
    status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    size = models.CharField(default=0, max_length=5)

    def items(self):
        cart_items = CartItemModel.objects.filter(
            cart=self,
            status=True,
        )
        return cart_items

    def total(self):
        amount = CartModel.objects.aggregate(
            amount=Sum(F("cartitemmodel__product__price") * F("cartitemmodel__quantity"))
        ).get("amount", 0)
        return amount

    def __str__(self):
        return f"{self.user}"


# Cart Item Model
class CartItemModel(models.Model):
    cart = models.ForeignKey(CartModel, on_delete=models.CASCADE)
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.product}({self.quantity})"

core/forms.py
from django import forms
from core import models


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = models.FeedbackModel
        # fields = "__all__" #["name", "message", "email", ]
        exclude = ('status', )
 #product

class ProductForm(forms.ModelForm):
    class Meta:
        model = models.ProductModel
        # fields = "__all__" #["name", "message", "email", ]
        exclude = ("status","created_on","updated_on" )


class CategoryForm(forms.ModelForm):
    class Meta:
        model = models.CategoryModel
        # fields = "__all__" #["name", "message", "email", ]
        exclude = ("status","created_on","updated_on" )

core/views.py
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic as views

from core import models as core_models
from core.forms import FeedbackForm, ProductForm
from user import models as user_models
from django.db.models import F, Q



# home view
class HomeView(views.TemplateView):
    template_name = "core/home.html"

    extra_context = {"products": core_models.ProductModel.objects.filter(status=True)}


# about_us view
class AboutView(views.TemplateView):
    template_name = "core/about_us.html"




# ================================= FEEDBACK ================================= #


# feedback create view
class FeedbackCreateView(views.CreateView):
    template_name = "core/feedback_create.html"
    model = core_models.FeedbackModel
    form_class = FeedbackForm
    success_url = reverse_lazy("core:home")


class FeedbackListView(views.ListView):
    template_name = "core/feedback_list.html"
    model = core_models.FeedbackModel
    form_class = FeedbackForm
    success_url = reverse_lazy("core:home")


class FeedbackDeleteView(views.ListView):
    template_name = "core/feedback_delete.html"
    model = core_models.FeedbackModel
    form_class = FeedbackForm
    success_url = reverse_lazy("core:home")


class FeedbackDetailView(views.ListView):
    template_name = "core/feedback_detail.html"
    model = core_models.FeedbackModel
    form_class = FeedbackForm
    success_url = reverse_lazy("core:home")


class FeedbackUpdateView(views.ListView):
    template_name = "core/feedback_update.html"
    model = core_models.FeedbackModel
    form_class = FeedbackForm
    success_url = reverse_lazy("core:home")


# ================================= FEEDBACK END ================================= #


# ================================= PRODUCT START ================================= #

# Product list
class ProductListView(views.ListView):
    template_name = "core/product_list.html"
    model = core_models.ProductModel
    context_object_name = "products"


# Product create
class ProductCreateView(views.CreateView):
    template_name = "core/product_create.html"
    model = core_models.ProductModel
    form_class = ProductForm
    success_url = reverse_lazy("core:product_list")


# Product detail
class ProductDetailView(views.DetailView):
    template_name = "core/product_detail.html"
    model = core_models.ProductModel
    context_object_name = "product"


# Product update
class ProductUpdateView(views.UpdateView):
    template_name = "core/product_update.html"
    model = core_models.ProductModel
    form_class = ProductForm
    success_url = reverse_lazy("core:product_list")


# Product delete
class ProductDeleteView(views.DeleteView):
    template_name = "core/product_delete.html"
    model = core_models.ProductModel
    success_url = reverse_lazy("core:product_list")


# ================================= PRODUCT END ================================= #


# ================================= CATEGORY START ================================= #


class ProductByCategoryView(views.ListView):
    template_name = "core/product_list.html"
    model = core_models.ProductModel
    context_object_name = "products"

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        pk = self.kwargs.get("pk", None)
        qs = qs.filter(category__id=pk)
        return qs


class CategoryListView(views.ListView):
    template_name = "core/category/category_list.html"
    model = core_models.CategoryModel
    context_object_name = "categories"


# =================================CATEGORY END================================= #

# cart


class AddToCartView(views.View):
    def get(self, request, pk):
        # try:
        user = request.user
        product = core_models.ProductModel.objects.get(id=pk)
        cart, cart_created = core_models.CartModel.objects.get_or_create(
            user=user, checked_out=False
        )
        cart_item, cart_item_created = core_models.CartItemModel.objects.get_or_create(
            cart=cart, product=product
        )
        if not cart_item_created:
            cart_item.quantity += 1

        cart_item.save()
        messages.success(request, "Product added successfully!")
        # except Exception as e:
        #     print(e)
        #     messages.error(request, f"Product couldn't add! ERROR:-{e}")
        url = request.META.get("HTTP_REFERER")
        return redirect(url)


# cart
class CartView(views.TemplateView):
    template_name = "core/checkout/cart.html"


# cartremove
class CartDeleteView(views.DeleteView):
    template_name = "core/checkout/cart_delete.html"
    model = core_models.CartModel


# delivery
class DeliveryView(views.TemplateView):
    model = user_models.AddressModel
    template_name = "core/delivery/delivery_address.html"
    context_object_name = "addresss"


# shipment
class ShipmentView(views.TemplateView):
    template_name = "core/delivery/shipment_details.html"


# order summary


class OrdersummaryView(views.TemplateView):
    template_name = "core/delivery/order_summary.html"


# order placed
class OrderplacedView(views.TemplateView):
    template_name = "core/orderplaced/ordr_placed.html"


# checkout
class CheckoutView(views.TemplateView):
    template_name = "core/checkout/checkout.html"


class CancelorderView(views.TemplateView):
    template_name = "core/checkout/cancelorder.html"


class CanceltemplateView(views.TemplateView):
    template_name = "core/checkout/canceltemplate.html"


# payment
class PaymentView(views.TemplateView):
    template_name = "core/payment/payment.html"


# payment success
class PaymentsuccessView(views.TemplateView):
    template_name = "core/payment/paysuccess.html"


# add more  details
class AdddetailView(views.TemplateView):
    template_name = "core/user/add_details.html"


# add new address
class AddnewaddressView(views.TemplateView):
    template_name = "user/addnew_address.html"

# dashbboard
class DashboardView(views.TemplateView):
    template_name = "core/dashboard/dashboard.html"

#search
class ProductSearchView(views.ListView):
    template_name = "core/list.html"
    model = core_models.ProductModel
    context_object_name = "products"

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        q = self.request.GET.get("q", None)
        qs = qs.filter(Q(name__icontains=q) | Q(category__name__icontains=q))
        return qs

templates/core/checkout/cancelorder.html
{% extends 'base.html' %}
{% block content %}

<div class="card m-5">
    <section style="background-color: rgb(245, 233, 235);">
    <div class="text-center m-5">
        
        <h8>
            ARE YOU SURE YOU WANT TO DELETE THIS ORDER !  
        </h8>
        <i class="fa-solid fa-face-sad-tear"></i>   
   </div>
   <div class="text-center m-5">
   
   <button class="btn1"><a href="{% url 'core:canceltemplate' %}">YES </button></a>
   <button class="btn1"><a href="{% url 'core:ordersummary' %}">NO </button></a>
 </div>
</div>
</section>
{% endblock %}

templates/core/checkout/canceltemplate.html
{% extends "base.html" %} {% block content %}
<section style="background-color: rgb(245, 233, 235);">
    <div class="text-center m-">
       
        <p>
        <img src="/media/product/odc.jpeg"></p>
    </div>
</section>
{% endblock content %}

templates/core/checkout/cart.html
{% extends 'base.html' %}
{% block content %}
<section style="background-image: url(https://media.istockphoto.com/id/1094721986/vector/abstract-of-pink-living-coral-color-sky-background.jpg?s=612x612&w=0&k=20&c=dGDrG_m4WNfCFAcYRFBSrIcS2QnhLlzIs1FDGqkjnG8=)">
<div class="m-5">
    <i><h2>CART</h2></i>
    <div class="row">
      <div class="prod">
        <ol style="color:rgb(235, 60, 89)">
        <b><h5 class="text-center"> ITEMS IN CART</h5></b></ol>
      </div>
      <div class="card ">
        {% for item in cart.items %}
        <p>{{item.product}}<br>&pound;{{item.product.price}}</p>
        <p>{{item.description}}{{item.product.description}}</p>
       <a href="{% url 'core:product_detail' item.product.id %}"
      >
        <p>{{item}}</p>
        <div class="text-center">
        <button class="checkout"><a href="{% url 'core:cart_delete' %}">Remove</button></a>
        </div>
        {% empty %}
        <li>Nothing Found!</li>
        {% endfor %}
 
    </div>
</div>
</div>
  <div class="text-center">
    <button class="checkout"><a href="{% url 'core:checkout' %}">checkout</button></a>
  </div>
</section>

    
{% endblock %}

templates/core/checkout/cart_delete.html
{% extends 'base.html' %} 
{% block content %}

{% for item in cart_items %}
{{ item.remove }}
{% endfor %}


{% endblock content %}

templates/core/checkout/checkout.html
{% extends 'base.html' %}
{% block content %}
<section style="background-image: url(https://media.istockphoto.com/id/1094721986/vector/abstract-of-pink-living-coral-color-sky-background.jpg?s=612x612&w=0&k=20&c=dGDrG_m4WNfCFAcYRFBSrIcS2QnhLlzIs1FDGqkjnG8=)">
  <div class="m-5">
    <i><h2>CHECK OUT</h2></i>
    <div class="row">
      <div class="prod">
      </div>
      <div class="column">
        {% for item in cart.items %}
        <p>{{item}}<br>&pound;{{item.product.price}}</p>
        <p>{{item.description}}{{item.product.description}}</p>
        <p>size:{{item.size}}{{item.product.size}}</p>

       
        <!-- <label> Size:</label> -->
        <!-- <select>
          <option value="visa">Xs</option>
          <option value="Rupay">S</option>
          <option value="visa">M</option>
          <option value="Rupay">L</option>
          <option value="Rupay">Xl</option>
          <option value="Rupay">Xxl</option>
          <option value="Rupay">Kg</option>
          <option value="Rupay">G</option>
          <option value="Rupay">L</option>
          <option value="Rupay">Ml</option>
       </select> -->
        {% empty %}
        <li>Nothing Found!</li>
        {% endfor %}
        
  <ul class="dropdown-menu">
    <li class="dropdown-item d-flex justify-content-between fw-bold">
      <span>Item</span>
      <span>Qty</span>
    </li>
    {% for item in cart.items %}
    <li class="dropdown-item d-flex justify-content-between">
      <a
        class="link-primary"
        href="{% url 'core:product_detail' item.product.id %}"
      >
        {{item.product}}
      </a>
      <span class="fw-bold">{{item.quantity}}</span>
    </li>
    {% empty %}
    <li>Nothing Found!</li>
    {% endfor %}
    <li class="dropdown-item d-flex justify-content-between fw-bold text-bg-primary">
      <a href="{% url 'core:checkout' %}" class="link-light">Checkout</a>
    </li>
  </ul>   
    </div>
  </div>
  <div class="text-center">
    <button class="checkout" id="checkout"> <a href="{% url 'core:cart' %}">Return To Cart</button>
    <button class="checkout" id="checkout"><a href="{% url 'core:delivery' %}">Checkout</button></a>
  </div>
  </div>
</section>
{% endblock %}