Ecart/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static 
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("user/", include("user.urls", namespace="user")),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  

core/urls.py
from django.urls import path
from core import views

app_name = "core"
urlpatterns = [
    # Common
    path("", views.HomeView.as_view(), name="home"),
    path("about_us/", views.AboutView.as_view(), name="about_us"),
    # Feedback
    path(
        "feedback/create/", views.FeedbackCreateView.as_view(), name="feedback_create"
    ),
    path("feedback/list/", views.FeedbackListView.as_view(), name="feedback_list"),
    path(
        "feedback/<int:pk>/delete/",
        views.FeedbackDeleteView.as_view(),
        name="feedback_delete",
    ),
    path(
        "feedback/<int:pk>/detail/",
        views.FeedbackDetailView.as_view(),
        name="feedback_detail",
    ),
    path(
        "feedback/<int:pk>/update/",
        views.FeedbackUpdateView.as_view(),
        name="feedback_update",
    ),
    # Product
    path("product/list/", views.ProductListView.as_view(), name="product_list"),
    path("product/create/", views.ProductCreateView.as_view(), name="product_create"),
    path(
        "product/<int:pk>/detail/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
    path(
        "product/<int:pk>/update/",
        views.ProductUpdateView.as_view(),
        name="product_update",
    ),
    path(
        "product/<int:pk>/delete/",
        views.ProductDeleteView.as_view(),
        name="product_delete",
    ),
    # category
    path("category/list/", views.CategoryListView.as_view(), name="category_list"),
    path("product_by_category/<int:pk>/list/",views.ProductByCategoryView.as_view(), name="product_by_category",),
   
    # Cart
    path("cart/product/<int:pk>/add/", views.AddToCartView.as_view(), name="add_to_cart"),
    path("cart/", views.CartView.as_view(), name="cart"),
    path("cart_delete/", views.CartView.as_view(), name="cart_delete"),

    # delivery
    path("delivery/", views.DeliveryView.as_view(), name="delivery"),
    # shipment
    path("shipment/", views.ShipmentView.as_view(), name="shipment"),
    # ordersummary
    path("ordersummary/", views.OrdersummaryView.as_view(), name="ordersummary"),
    #orderplaced
     path("ordr_placed/", views.OrderplacedView.as_view(), name="ordr_placed"),
    # checkout
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    # cancelorder
    path("cancelorder/", views.CancelorderView.as_view(), name="cancelorder"),
     # canceltemplate
    path("canceltemplate/", views.CanceltemplateView.as_view(), name="canceltemplate"),
    # payment
    path("payment/", views.PaymentView.as_view(), name="payment"),
    # payment success
    path("paymentsuccess/", views.PaymentsuccessView.as_view(), name="paymentsuccess"),
    path("add_details/", views.AdddetailView.as_view(), name="add_details"),
    path("addnew_address/", views.AddnewaddressView.as_view(), name="addnew_address"),
    #dashboard
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    #search
    path("product/search/",views.ProductSearchView.as_view(),name="product_search"),



]

user/urls.py
from core import views
from django.urls import path

from user import views

app_name = "user"

urlpatterns = [
    path("signup/", views.UserCreateView.as_view(), name="user_signup"),
    path("login/", views.UserLoginView.as_view(), name="user_login"),
    path("logout/", views.UserLogoutView.as_view(), name="user_logout"),
    # address
    path("address/create/", views.AddressCreateView.as_view(), name="address_create"),

    # 
    path("profile/create/", views.ProfileCreateView.as_view(), name="profile_create"),
    path("profile/detail/", views.ProfileDetailView.as_view(), name="profile_detail"),
    path("profile/<int:pk>/update/",views.ProfileUpdateView.as_view(),name="profile_update"), 
    
]

user/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass


USER = settings.AUTH_USER_MODEL


class LocationModel(models.Model):
    lattitude = models.FloatField()
    longitude = models.FloatField()
    

    def __str__(self):
        return f"{self.lattitude},{self.longitude}"


class AddressModel(models.Model):

    building_name = models.CharField(max_length=64)
    place = models.CharField(max_length=32)
    city = models.CharField(max_length=32)
    district = models.CharField(max_length=32)
    state = models.CharField(max_length=32)
    country = models.CharField(max_length=24, default="India")
    postal_code = models.CharField(max_length=6)
    location = models.ForeignKey(
        LocationModel, on_delete=models.SET_NULL, null=True, blank=True
    )
    status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.building_name},{self.place}-{self.postal_code}"


class ProfileModel(models.Model):
    GENDER_CHOICES = (
        ("M", "Male"),
        ("F", "Female"),
        ("T", "Transgender"),
    )
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    gender = models.CharField(max_length=15, choices=GENDER_CHOICES)
    image = models.ImageField(upload_to="user/profile/image/", default="default/user.png")
    phone_number = models.CharField(max_length=15)
    address = models.ManyToManyField(AddressModel, blank=True)
    user = models.OneToOneField(USER, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}".title()

user/forms.py
from django import forms
from user import models as user_models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

USER = get_user_model()

# User Registration Form
class UserRegisterform(UserCreationForm):
    class Meta:
        model = USER
        fields = ["email", "username"]


# Profile Form
class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        super().__init__(*args, **kwargs)
        self.fields["address"].queryset = request.user.profilemodel.address.all()

    class Meta:
        model = user_models.ProfileModel
        exclude = (
            "status",
            "created_on",
            "updated_on",
        )


class AddressForm(forms.ModelForm):
    class Meta:
        model = user_models.AddressModel
        exclude = ("status",)

user/views.py
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import forms as auth_forms
from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic as views

from user import forms as user_form
from user import models as user_models
from user.forms import ProfileForm

USER = get_user_model()

# UserCreateView
class UserCreateView(views.CreateView):
    template_name = "registration/signup.html"
    form_class = user_form.UserRegisterform
    success_url = reverse_lazy("user:user_login")


class UserLoginView(views.View):
    form_class = auth_forms.AuthenticationForm
    success_url = reverse_lazy("core:home")
    template_name = "registration/login.html"

    def get(self, request):
        context = {
            "form": self.form_class(),
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request=request)
        # if form.is_valid():
        form.is_valid()
        username = request.POST.get("username")
        password = request.POST.get("password")
        # to check whether the given username and password are exists or not
        user = authenticate(request, username=username, password=password)
        if user is not None:
            # to login user
            login(request, user)
            print("USER is valid.............LOGGED IN")
            return redirect(self.success_url)
        print("USER is not valid.............")
        print("FORM is not valid.............")
        context = {"form": form}
        return render(request, self.template_name, context)
        
class UserLogoutView(views.View):
    template_name = "registration/logged_out.html"

    def get(self, request):
        logout(request)
        messages.success(request, "Successfully Logged out")
        return render(request, self.template_name)


# profile create view
class ProfileCreateView(views.CreateView):
    template_name = "user/profile_create.html"
    model = user_models.ProfileModel
    form_class = ProfileForm
    success_url = reverse_lazy("user:profile_detail")


# feedback updateview
class ProfileUpdateView(views.UpdateView):
    template_name = "user/profile_update.html"
    model = user_models.ProfileModel
    form_class = ProfileForm
    success_url = reverse_lazy("user:profile_detail")
    extra_context = {"address_form": user_form.AddressForm}

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        try:
            address = self.request.user.profilemodel.address.all()
        except:
            address = None
        kwargs.update({"request": self.request, "initial": {"address": address}})
        return kwargs


class ProfileDetailView(views.TemplateView):
    template_name = "user/profile_detail.html"
    model = user_models.ProfileModel
    context_object_name = "profile"


# Address
class AddressCreateView(LoginRequiredMixin, views.FormView):
    template_name = "core/address/address_create.html"
    form_class = user_form.AddressForm

    def form_valid(self, form):
        address = form.save()
        self.request.user.profilemodel.address.add(address)
        messages.success(self.request, message="Address created successfully!")
        return super().form_valid(form)

    def get_success_url(self):
        url = self.request.META.get("HTTP_REFERER", "/")
        return url

templates/user/add_details.html
{% extends 'base.html' %}
 {% block content %}
 <section style="min-height:100vh">
  <div class="m-5">
  <i> <h2>User Details</h2></i>
  <div class="form-group">
    <label for="pwd"> Flat/House no/ Building:</label>
    <span class="fa fa-home"></span>
    <input
      type="Delivery Address"
      class="form-control"
      id="Delivery Address"
      placeholder="Enter Delivery Address"
      name="Delivery Address"
    />
  </div>
 

  <div class="form-group">
    <label for="pwd"> Nearby location:</label>
    <span class="fa fa-building"></span>
    <input type="Nearby location" class="form-control" id="Nearby locations" />
  </div>

  <div class="form-group">
    <label for="checkout-postal">Postal code :</label>
      <span class="fa fa-archive"></span>
      <input
        type="numeric"
        name="checkout-postal"
        id="checkout-postal"
        class="form-control"
        placeholder="Your postal code..."
      />
  </div>

  <div class="form-group">
    <label for="checkout-phone"> Alternative Contact :</label>
      <span class="fa fa-phone"></span>
      <input
        type="tel"
        name="checkout-phone"
        id="checkout-phone"
        class="form-control"
        placeholder="Enter you phone no...."
      />
    </div>
    <div class="form-group">
      <label for="city"> City / Street :</label>
        <span class="fa fa-city"></span>
        <input
          type="city"
          name="city"
          id="city"
          class="form-control"
          
        />
      </div>
      <div class="form-group">
        <label for="state"> State :</label>
          <input
            type="state"
            name="state"
            id="state"
            class="form-control"
           
          />
        </div>
        <div class="form-group">
          <label for="checkout-phone"> Country :</label>
            <span class="fa fa-flag"></span>
            <input
              type="country"
              name="country"
              id="country"
              class="form-control"
            />
          </div>
          <button class="btn1" class="btn1">submit</button>
  </div>
</section>


{% endblock %}

templates/user/addnew_address.html
{% extends 'base.html' %} 
{% block content %}

<section style="min-height:100vh">
  <div class="m-5">
  <i> <h2>User Details</h2></i>
  <div class="form-group">
    <label for="city">  Name :</label>
      <span class="fa fa-user"></span>
      <input
        type="user"
        name="user"
        id="user"
        class="form-control"
        
      />
    </div>

  <div class="form-group">
    <label for="checkout-phone"> Contact no :</label>
      <span class="fa fa-phone"></span>
      <input
        type="tel"
        name="checkout-phone"
        id="checkout-phone"
        class="form-control"
      />
    </div>
    <div class="form-group">
        <label for="pwd"> Delivery Address:</label>
        <span class="fa fa-home"></span>
        <input
          type="Delivery Address"
          class="form-control"
          id="Delivery Address"
          placeholder="Enter Delivery Address"
          name="Delivery Address"
        />
      </div>
     
      <div class="form-group">
        <label for="city"> Nearby location :</label>
          <span class="fa fa-city"></span>
          <input
            type="city"
            name="city"
            id="city"
            class="form-control"
            
          />
        </div>
        

          <div class="form-group">
            <label for="checkout-postal">Postal code :</label>
              <span class="fa fa-archive"></span>
              <input
                type="numeric"
                name="checkout-postal"
                id="checkout-postal"
                class="form-control"
                placeholder="Your postal code..."
              />
          </div>
          <button class="btn1" class="btn1">Save Address</button>
  </div>
  </section>
{% endblock %}

templates/user/profile_create.html
{% extends 'base.html' %} {% block content %}
<section>
    <div class="container py-5" style="min-height:100vh ;">
        <div class="row">
          <h1 class="text-light">Create Profile</h1>    
          <div class="col-lg-6">
            <div class="card">
              <div class="card-body">
                <form action="" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  <table>
                    <tbody>
                      {{form.as_p}}
                    </tbody>
                  </table>
                  <button class="btn btn-primary" type="submit">Submit</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
</section>
{% include 'includes/footer.html' %}
{% endblock content %}

templates/user/profile_detail.html
{% extends 'base.html' %}{% block content %}

<section class="gradient-custom-2" style="min-height: 100vh">
  <div>
    <a href="{% url 'core:home' %}">
      <h1 class="poppins text-center text-white pt-5">ecart</h1>
    </a>
  </div>
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card">
          <div
            class="rounded-top text-white d-flex flex-row"
            style="background-color: #000; height: 200px"
          >
            <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px">
              {% if user.profilemodel %}
              <img
                id="profileImage"
                src="{{user.profilemodel.image.url}}"
                alt="Generic placeholder image"
                class="img-fluid img-thumbnail mt-4 mb-2"
                style="width: 140px; z-index: 1"
              />

              <a
                href="{% url 'user:profile_update' user.profilemodel.id %}"
                class="btn btn-primary"
                >Edit profile
              </a>
            </div>
            <div class="ms-3" style="margin-top: 130px">
              <h5 class="text-capitalize">{{user.profilemodel.user}}</h5>
              <p>{{user.profilemodel.city}}Kochi</p>
            </div>
          </div>
          <div class="p-4 text-black" style="background-color: #f8f9fa">
            <div class="d-flex justify-content-end text-center py-1">
              <div class="mx-3">
                <p class="mb-1 h5"><i class="fa-regular fa-heart"></i></p>
                <p class="small text-muted mb-0">Favourites</p>
              </div>
              <div lass="mx-3">
                <p class="mb-1 h5">478</p>
                <p class="small text-muted mb-0">Following</p>
              </div>
            </div>
          </div>
          <div class="card-body p-4 text-black">
            <div class="mb-5">
              <p class="lead fw-normal mb-1">About</p>
              <div class="p-4" style="background-color: #f8f9fa">
                <p class="font-italic mb-1 text-capitalize">
                  First_name : {{user.profilemodel.first_name}}
                </p>
                <p class="font-italic mb-1 text-capitalize">
                  Last_name : {{user.profilemodel.last_name}}
                </p>
                <p class="font-italic mb-1 text-capitalize">
                  Gender : {{user.profilemodel.gender}}
                </p>
                <p class="font-italic mb-1">
                  phone_number : {{user.profilemodel.phone_number}}
                </p>
                <div>
                  {% for address in user.profilemodel.address.all %}
                  <p>address : {{address}}</p>
                  {% endfor %}
                </div>
                <form
                  action="{% url 'user:profile_update' user.profilemodel.id %}"
                  id="profileimageupdate"
                  enctype="multipart/form-data"
                >
                  {% csrf_token %}
                  <input
                    id="imageUpload"
                    type="file"
                    name="profile_photo"
                    placeholder="Photo"
                    required=""
                    capture
                  />
                </form>
              </div>
            </div>
            {% else %}
            <tr>
              <td colspan="4">
                <a href="{% url 'user:profile_create' %}" class="text-light">
                  Create Profile
                </a>
              </td>
            </tr>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% include 'includes/footer.html' %} {% endblock content %}

templates/user/profile_update.html
{% extends 'base.html' %} {% block content %}

<section class="py-5" style="min-height: 100vh">
  <!-- add address modal START -->
  <!-- Button trigger modal -->

  <!-- Modal -->
  <div
    class="modal fade"
    id="add_address_modal"
    data-bs-backdrop="static"
    data-bs-keyboard="false"
    tabindex="-1"
    aria-labelledby="add_address_modal_label"
    aria-hidden="true"
  >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="add_address_modal_label">
            Add address
          </h1>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">
          <form action="{% url 'user:address_create' %}" method="post">
            {% csrf_token %} {{address_form.as_p}}
            <div class="btn-group">
              <button
                type="button"
                class="btn btn-secondary"
                data-bs-dismiss="modal"
              >
                Close
              </button>
              <button type="submit" class="btn btn-primary">Create</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- add address modal END -->
  <div class="container">
    <div class="row">
      <div class="col">
        <h2 class="text-center text-light">Profile Update</h2>
        <hr />
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <div class="card">
          <div class="card-body">
            <form action="" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <table>
                <tbody>
                  {{form.as_p}}
                </tbody>
              </table>
              <div class="d-flex justify-content-between align-items-center">
                <a
                  href="#add_address_modal"
                  class="link-primary mb-3"
                  data-bs-toggle="modal"
                >
                  Add address
                </a>
                <button class="btn btn-primary" type="submit">Submit</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% include 'includes/footer.html' %} {% endblock content %}